export const headerItems = {
  project: [
    "Code",
    "Location",
    "Group Name",
    "Pax",
    "Arrival",
    "Departure",
    "Status",
    "Estimate",
    "Delete",
    "Update",
  ],
  schedule: [
    "Code",
    "Start Date",
    "End Date",
    "Group Name",
    "Location",
    "Nr of Pax",
  ],
  projectBase: [
    "Days",
    "Morning Events",
    "Lunch Options",
    "Afternoon Events",
    "Dinner Options",
  ],
  transferVendor: [
    "Company",
    "Vehicle Type",
    "Number of Vehicles",
    "Add to Schedule",
  ],
  restaurant: ["Name", "City", "Price", "Is a Venue"],
  event: ["Name", "City", "Price"],
  accManager: ["First Name", "Family Name", "Email"],
  client: ["Name", "Email", "Company", "Country"],
  country: ["Name", "Web Code", "Quote Language"],
  hotel: ["Name", "Stars", "Address", "Rooms", "Meeting Rooms"],
};
